// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjebquqdpvavbronrvxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqZWJxdXFkcHZhdmJyb25ydnhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTc4NDUsImV4cCI6MjA2NDU5Mzg0NX0.T-4h7_6aSWkculSRrxTol17rGk1UKW3-bdkJnwYPLvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);